#if !canImport(ObjectiveC)
import XCTest

extension Exercice1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Exercice1Tests = [
        ("testFibo", testFibo),
        ("testIsPalindrome", testIsPalindrome),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Exercice1Tests.__allTests__Exercice1Tests),
    ]
}
#endif
