#if !canImport(ObjectiveC)
import XCTest

extension HomeworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HomeworkTests = [
        ("testContains", testContains),
        ("testCount", testCount),
        ("testEquality", testEquality),
        ("testIntersection", testIntersection),
        ("testSubtracting", testSubtracting),
        ("testUnion", testUnion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HomeworkTests.__allTests__HomeworkTests),
    ]
}
#endif
