#if !canImport(ObjectiveC)
import XCTest

extension HomeworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HomeworkTests = [
        ("testAll", testAll),
        ("testAxiom", testAxiom),
        ("testChoice", testChoice),
        ("testFail", testFail),
        ("testIdentity", testIdentity),
        ("testInnermost", testInnermost),
        ("testOuterMost", testOuterMost),
        ("testSequence", testSequence),
        ("testSubstitution", testSubstitution),
        ("testTry", testTry),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HomeworkTests.__allTests__HomeworkTests),
    ]
}
#endif
