#if !canImport(ObjectiveC)
import XCTest

extension ADTTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ADTTests = [
        ("testBool", testBool),
        ("testInt", testInt),
        ("testNat", testNat),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ADTTests.__allTests__ADTTests),
    ]
}
#endif
